export const ADD_ITEM_TO_CART_START = 'ADD_ITEM_TO_CART_START';
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
