export const CHECK_OLD_ITEMS = 'CHECK_OLD_ITEMS';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const INCREMENT_ITEM = 'INCREMENT_ITEM';
export const DECREMENT_ITEM = 'DECREMENT_ITEM';
