# Generated by Django 3.2.6 on 2021-08-27 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_name', models.CharField(max_length=255, verbose_name='Variant Name')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
            ],
            options={
                'unique_together': {('v_name', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ItemVariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=5)),
                ('varaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.itemvariant')),
            ],
            options={
                'unique_together': {('value', 'varaint')},
            },
        ),
    ]
