# Generated by Django 3.2.6 on 2021-08-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_itemvariant_itemvariantoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_v', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='itemvariantoption',
            name='varaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_options', to='menu.itemvariant'),
        ),
    ]
